language: java

jdk:
  - openjdk9

sudo: false

env:
  global:
    - CODECOV_TOKEN="554e9f10-af85-422a-85b1-70e935b08817"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - fandvor@mail.ru
    on_success: never # default: change
    on_failure: always # default: always